name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Make artifact
      run: |
        echo ${{ github.event.pull_request.head.sha }} >> rand_num.out
        echo                   >> rand_num.out
        git log -n 5           >> rand_num.out
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: random-${{ github.event.pull_request.head.sha }}
        path: rand_num.out
